export const SHOP_INFO = {
  name: 'ApnaMart',
  tagline: 'One store. Fast local delivery.',
  etaMinutes: 12,
  minimumOrderValue: 100,
  freeDeliveryAbove: 399,
  deliveryFee: 0,
  handlingFee: 5,
  taxRate: 0.03,
  // serviceArea: ['Sector 3', 'Sector 7', 'Main Bazar', 'Green Colony'],
}

export const CATEGORIES = [
  'All',
  'Fruits',
  'Vegetables',
  'Dairy',
  'Snacks',
  'Beverages',
  'Bakery',
  'Household',
]

// export const PRODUCTS = [
//   {
//     id: 'fr-apple',
//     name: 'Apple Royal Gala',
//     category: 'Fruits',
//     unit: '1 kg',
//     price: 159,
//     originalPrice: 189,
//     stock: 30,
//     eta: 10,
//     badge: 'Best Seller',
//     image: '🍎',
//   },
//   {
//     id: 'fr-banana',
//     name: 'Banana Robusta',
//     category: 'Fruits',
//     unit: '1 dozen',
//     price: 52,
//     originalPrice: 65,
//     stock: 40,
//     eta: 8,
//     badge: 'Daily Essential',
//     image: '🍌',
//   },
//   {
//     id: 'fr-orange',
//     name: 'Nagpur Orange',
//     category: 'Fruits',
//     unit: '1 kg',
//     price: 99,
//     originalPrice: 119,
//     stock: 35,
//     eta: 11,
//     badge: 'Fresh Arrival',
//     image: '🍊',
//   },
//   {
//     id: 've-potato',
//     name: 'Farm Potato',
//     category: 'Vegetables',
//     unit: '1 kg',
//     price: 36,
//     originalPrice: 45,
//     stock: 55,
//     eta: 10,
//     badge: 'Budget Pick',
//     image: '🥔',
//   },
//   {
//     id: 've-onion',
//     name: 'Onion Premium',
//     category: 'Vegetables',
//     unit: '1 kg',
//     price: 44,
//     originalPrice: 54,
//     stock: 45,
//     eta: 10,
//     badge: 'High Demand',
//     image: '🧅',
//   },
//   {
//     id: 've-tomato',
//     name: 'Tomato Hybrid',
//     category: 'Vegetables',
//     unit: '1 kg',
//     price: 42,
//     originalPrice: 49,
//     stock: 44,
//     eta: 9,
//     badge: 'Fresh Cut',
//     image: '🍅',
//   },
//   {
//     id: 'da-milk',
//     name: 'Full Cream Milk',
//     category: 'Dairy',
//     unit: '1 L',
//     price: 64,
//     originalPrice: 70,
//     stock: 80,
//     eta: 8,
//     badge: 'Top Rated',
//     image: '🥛',
//   },
//   {
//     id: 'da-curd',
//     name: 'Fresh Curd',
//     category: 'Dairy',
//     unit: '400 g',
//     price: 45,
//     originalPrice: 52,
//     stock: 50,
//     eta: 8,
//     badge: 'Today Made',
//     image: '🥣',
//   },
//   {
//     id: 'da-paneer',
//     name: 'Malai Paneer',
//     category: 'Dairy',
//     unit: '200 g',
//     price: 94,
//     originalPrice: 112,
//     stock: 33,
//     eta: 12,
//     badge: 'Chef Choice',
//     image: '🧀',
//   },
//   {
//     id: 'sn-chips',
//     name: 'Masala Chips',
//     category: 'Snacks',
//     unit: '120 g',
//     price: 30,
//     originalPrice: 35,
//     stock: 60,
//     eta: 7,
//     badge: 'Combo Deal',
//     image: '🍟',
//   },
//   {
//     id: 'sn-namkeen',
//     name: 'Khatta Meetha Mix',
//     category: 'Snacks',
//     unit: '250 g',
//     price: 68,
//     originalPrice: 78,
//     stock: 40,
//     eta: 9,
//     badge: 'Tea Time',
//     image: '🥜',
//   },
//   {
//     id: 'sn-biscuits',
//     name: 'Butter Biscuits',
//     category: 'Snacks',
//     unit: '300 g',
//     price: 52,
//     originalPrice: 60,
//     stock: 65,
//     eta: 8,
//     badge: 'Family Pack',
//     image: '🍪',
//   },
//   {
//     id: 'be-cola',
//     name: 'Cola Drink',
//     category: 'Beverages',
//     unit: '750 ml',
//     price: 44,
//     originalPrice: 55,
//     stock: 47,
//     eta: 8,
//     badge: 'Party Pick',
//     image: '🥤',
//   },
//   {
//     id: 'be-juice',
//     name: 'Mixed Fruit Juice',
//     category: 'Beverages',
//     unit: '1 L',
//     price: 99,
//     originalPrice: 115,
//     stock: 38,
//     eta: 10,
//     badge: 'No Added Color',
//     image: '🧃',
//   },
//   {
//     id: 'be-water',
//     name: 'Mineral Water',
//     category: 'Beverages',
//     unit: '2 L',
//     price: 24,
//     originalPrice: 28,
//     stock: 90,
//     eta: 7,
//     badge: 'Fast Moving',
//     image: '💧',
//   },
//   {
//     id: 'ba-bread',
//     name: 'Brown Bread',
//     category: 'Bakery',
//     unit: '400 g',
//     price: 46,
//     originalPrice: 52,
//     stock: 42,
//     eta: 8,
//     badge: 'Fresh Bake',
//     image: '🍞',
//   },
//   {
//     id: 'ba-bun',
//     name: 'Burger Buns',
//     category: 'Bakery',
//     unit: '4 pcs',
//     price: 38,
//     originalPrice: 45,
//     stock: 36,
//     eta: 8,
//     badge: 'Soft Pack',
//     image: '🥯',
//   },
//   {
//     id: 'ba-cake',
//     name: 'Mini Choco Cake',
//     category: 'Bakery',
//     unit: '250 g',
//     price: 139,
//     originalPrice: 165,
//     stock: 24,
//     eta: 12,
//     badge: 'Sweet Treat',
//     image: '🎂',
//   },
//   {
//     id: 'ho-detergent',
//     name: 'Liquid Detergent',
//     category: 'Household',
//     unit: '1 L',
//     price: 179,
//     originalPrice: 210,
//     stock: 30,
//     eta: 12,
//     badge: 'Value Pack',
//     image: '🧴',
//   },
//   {
//     id: 'ho-dishwash',
//     name: 'Dishwash Gel',
//     category: 'Household',
//     unit: '750 ml',
//     price: 96,
//     originalPrice: 110,
//     stock: 35,
//     eta: 11,
//     badge: 'Kitchen Care',
//     image: '🫧',
//   },
//   {
//     id: 'ho-tissue',
//     name: 'Tissue Roll Pack',
//     category: 'Household',
//     unit: '6 rolls',
//     price: 122,
//     originalPrice: 145,
//     stock: 29,
//     eta: 12,
//     badge: 'Home Must-Have',
//     image: '🧻',
//   },
// ]
